spring.application.name=party-finder

# MySQL 연결 설정
spring.datasource.url=jdbc:mysql://localhost:3306/party_db?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정 (테이블 자동 생성)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Clerk JWT 토큰 검증 주소 추가
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://fancy-walleye-76.clerk.accounts.dev/.well-known/jwks.json